/**
 * ============================================================================
 * TYPE DEFINITIONS - TypeScript Types & Interfaces
 * ============================================================================
 * 
 * This file contains all the TypeScript type definitions for the app.
 * TypeScript uses these types to catch errors at compile time.
 * 
 * WHAT IS TYPESCRIPT?
 * ------------------
 * TypeScript is JavaScript with types. It adds:
 * - Type checking (catches errors before running code)
 * - Better autocomplete (IDE knows what properties exist)
 * - Self-documenting code (types explain what data looks like)
 * 
 * INTERFACES VS TYPES:
 * --------------------
 * Both define object shapes. We use:
 * - interface: For objects with clear structure (Speaker, Podcast)
 * - type: For unions of specific values (SpeakerTone, GeminiVoice)
 * 
 * ============================================================================
 */

/**
 * ============================================================================
 * SPEAKER INTERFACE
 * ============================================================================
 * 
 * Defines what a Speaker object looks like.
 * This matches the 'speakers' table in Supabase.
 * 
 * Each property has a type:
 * - string: Text (e.g., "John")
 * - number: Number (e.g., 25)
 * - string | null: Text or null (optional field)
 * 
 * ============================================================================
 */
export interface Speaker {
  /** Unique identifier (UUID) - automatically generated by Supabase */
  id: string;
  
  /** ID of the user who created this speaker - links to auth.users */
  user_id: string;
  
  /** Speaker's display name */
  name: string;
  
  /** Speaker's age (optional - can be null) */
  age: number | null;
  
  /** URL to the speaker's profile picture (optional) */
  profile_pic_url: string | null;
  
  /** How the speaker sounds (e.g., "warm", "energetic") */
  tone: string | null;
  
  /** Speaker's profession/expertise (e.g., "tech expert", "scientist") */
  career: string | null;
  
  /** Speaker's personality traits (e.g., "curious", "analytical") */
  personality: string | null;
  
  /** Gemini voice ID (e.g., "Zephyr", "Puck") - determines the voice */
  voice_id: string;
  
  /** When this speaker was created (ISO timestamp) */
  created_at: string;
  
  /** When this speaker was last updated (ISO timestamp) */
  updated_at: string;
}

/**
 * ============================================================================
 * PODCAST INTERFACE
 * ============================================================================
 * 
 * Defines what a Podcast object looks like.
 * This matches the 'podcasts' table in Supabase.
 * 
 * ============================================================================
 */
export interface Podcast {
  /** Unique identifier (UUID) */
  id: string;
  
  /** ID of the user who created this podcast */
  user_id: string;
  
  /** Podcast title (e.g., "AI in Healthcare") */
  title: string;
  
  /** What the podcast is about (optional) */
  topic: string | null;
  
  /** URL to uploaded source material file (optional) */
  source_material_url: string | null;
  
  /** Original filename of the source material */
  source_material_name: string | null;
  
  /** Additional notes for the AI to consider */
  notes: string | null;
  
  /** The generated conversation script */
  script: string | null;
  
  /**
   * Podcast status
   * 
   * - 'draft': Created but not yet generated
   * - 'generating': Audio is being created
   * - 'ready': Podcast is complete and playable
   * - 'error': Something went wrong during generation
   */
  status: 'draft' | 'generating' | 'ready' | 'error';
  
  /** URL to the generated audio file */
  audio_url: string | null;
  
  /** The formatted transcript of the conversation */
  transcript: string | null;
  
  /** Audio duration in seconds */
  duration: number | null;
  
  /** When this podcast was created */
  created_at: string;
  
  /** When this podcast was last updated */
  updated_at: string;
}

/**
 * ============================================================================
 * SPEAKER TONE TYPE
 * ============================================================================
 * 
 * A "union type" that restricts values to specific options.
 * 
 * WHY USE THIS?
 * ------------
 * Instead of allowing any string for tone, we restrict to known values.
 * This prevents typos and makes the code self-documenting.
 * 
 * Example: const tone: SpeakerTone = 'warm';  // ✅ Valid
 * Example: const tone: SpeakerTone = 'happy'; // ❌ Error: not a valid tone
 * 
 * ============================================================================
 */
export type SpeakerTone = 
  | 'warm'        // Soft, friendly tone
  | 'energetic'   // Excited, high-energy
  | 'calm'        // Relaxed, peaceful
  | 'professional' // Formal, business-like
  | 'youthful'    // Young, fresh
  | 'mature'      // Experienced, wise
  | 'casual'      // Informal, conversational
  | 'firm';       // Confident, authoritative

/**
 * ============================================================================
 * GEMINI VOICE TYPE
 * ============================================================================
 * 
 * Union type of all available Gemini voices.
 * Each voice has a unique sound and personality.
 * 
 * These are Google's prebuilt voices for the Gemini TTS model.
 * The names are inspired by mythology and astronomy.
 * 
 * ============================================================================
 */
export type GeminiVoice = 
  | 'Zephyr' | 'Puck' | 'Charon' | 'Kore' | 'Fenrir' | 'Leda'
  | 'Orus' | 'Aoede' | 'Callirrhoe' | 'Autonoe' | 'Enceladus' | 'Iapetus'
  | 'Umbriel' | 'Algieba' | 'Despina' | 'Erinome' | 'Algenib' | 'Rasalgethi'
  | 'Laomedeia' | 'Achernar' | 'Alnilam' | 'Schedar' | 'Gacrux' | 'Pulcherrima'
  | 'Achird' | 'Zubenelgenubi' | 'Vindemiatrix' | 'Sadachbia' | 'Sadaltager' | 'Sulafat';

/**
 * ============================================================================
 * VOICE DESCRIPTIONS
 * ============================================================================
 * 
 * Maps each voice to a short description of its sound.
 * Used in the UI to help users choose a voice.
 * 
 * Record<GeminiVoice, string> means:
 * - Keys must be GeminiVoice values
 * - Values must be strings
 * 
 * Example: VOICE_DESCRIPTIONS['Zephyr'] === 'Bright'
 * 
 * ============================================================================
 */
export const VOICE_DESCRIPTIONS: Record<GeminiVoice, string> = {
  'Zephyr': 'Bright',
  'Puck': 'Upbeat',
  'Charon': 'Informative',
  'Kore': 'Firm',
  'Fenrir': 'Excitable',
  'Leda': 'Youthful',
  'Orus': 'Firm',
  'Aoede': 'Breezy',
  'Callirrhoe': 'Easy-going',
  'Autonoe': 'Bright',
  'Enceladus': 'Breathy',
  'Iapetus': 'Clear',
  'Umbriel': 'Easy-going',
  'Algieba': 'Smooth',
  'Despina': 'Smooth',
  'Erinome': 'Clear',
  'Algenib': 'Gravelly',
  'Rasalgethi': 'Informative',
  'Laomedeia': 'Upbeat',
  'Achernar': 'Soft',
  'Alnilam': 'Firm',
  'Schedar': 'Even',
  'Gacrux': 'Mature',
  'Pulcherrima': 'Forward',
  'Achird': 'Friendly',
  'Zubenelgenubi': 'Casual',
  'Vindemiatrix': 'Gentle',
  'Sadachbia': 'Lively',
  'Sadaltager': 'Knowledgeable',
  'Sulafat': 'Warm',
};

/**
 * ============================================================================
 * TONE OPTIONS
 * ============================================================================
 * 
 * Array of objects for use in dropdown/select components.
 * Each object has:
 * - value: The internal value (stored in database)
 * - label: The display text (shown to users)
 * 
 * USAGE EXAMPLE:
 * --------------
 * <select>
 *   {TONE_OPTIONS.map(option => (
 *     <option key={option.value} value={option.value}>
 *       {option.label}
 *     </option>
 *   ))}
 * </select>
 * 
 * ============================================================================
 */
export const TONE_OPTIONS: { value: SpeakerTone; label: string }[] = [
  { value: 'warm', label: 'Warm' },
  { value: 'energetic', label: 'Energetic' },
  { value: 'calm', label: 'Calm' },
  { value: 'professional', label: 'Professional' },
  { value: 'youthful', label: 'Youthful' },
  { value: 'mature', label: 'Mature' },
  { value: 'casual', label: 'Casual' },
  { value: 'firm', label: 'Firm' },
];
